name: Build MAUI Android & Windows

on:
  push:
    branches: [ "Eshop_Build" ]
  pull_request:
    branches: [ "Eshop_Build" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui

    # -------------------------
    # Restore
    # -------------------------
    - name: Restore
      run: dotnet restore ./EShop/EShopNative.csproj

    # -------------------------
    # Build Android APK
    # -------------------------
    - name: Build Android APK
      run: dotnet publish ./EShop/EShopNative.csproj -c Release -f net8.0-android

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          **/bin/Release/net8.0-android/**/*.apk

    # -------------------------
    # Build Windows MSIX
    # -------------------------
    - name: Build Windows
      run: dotnet publish ./EShop/EShopNative.csproj -c Release -f net8.0-windows10.0.19041.0

    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: windows-msix
        path: |
          **/bin/Release/net8.0-windows10.0.19041.0/**/*.msix
